[project]
name = "stream-mx-inspector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.9.1",
    "uvloop>=0.21.0",
]
