log:
  console_level: "INFO"
  file_level: "ERROR"
  file_path: "logs/raw_message_processor.log"

producer:
  bootstrap_servers: "10.254.161.191:9092"
  master_topic: "PARSED_SUMMARY_MESSAGE_FROM_INSPECTOR"
  detail_topic: "PARSED_FULL_MESSAGE_FROM_INSPECTOR"
  compression_type: "gzip"
  max_request_size_mb: 3

consumer:
  bootstrap_servers: "10.40.74.164:9092, 10.40.74.165:9092, 10.40.74.166:9092"
  topic: "GUMI_MES_NASLOG_SPC"
  group_id: "PIPELINE_TEST_BY_SHYEON"

schema_registry:
  url: "http://localhost:8081"
