version: '3.8'
services:
  kafka-broker:
    image: lensesio/fast-data-dev:latest
    ports:
      - "9092:9092" # Kafka Broker
      - "3030:3030" # Web UI
    environment:
      - ADV_HOST=192.168.50.170
      - RUNTESTS=1
      - SAMPLEDATA=1
      - CONNECT_PORT=0
      - REGISTRY_PORT=0

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - /home/shyeon/data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
