# 전역 설정
env: "dev"

# 각 프로세서별 설정
raw_message_processor:
  log:
    level: "INFO"
    path: "logs/raw_message_processor.log"
  consumer:
    topic: "raw-messages"
    bootstrap_servers: "localhost:9092"
    group_id: "raw-processor-group"
  producer:
    master_topic: "summary-messages"
    detail_topic: "full-messages"
    bootstrap_servers: "localhost:9092"
    compression_type: "gzip"

parsed_message_writer:
  log:
    level: "INFO"
    path: "logs/parsed_message_writer.log"
  spark:
    app_name: "ParsedMessageWriter_Dev"
    master: "local[*]"
  kafka:
    topic: "summary-messages"
    bootstrap_servers: "localhost:9092"
    group_id: "parsed-writer-group"
  iceberg:
    catalog_name: "dev_catalog"
    catalog_uri: "jdbc:postgresql://localhost:5432/dev_metastore"
    warehouse: "s3a://dev-bucket/warehouse"
    table: "dev_catalog.db.summary_logs"
